MANUAL_HOME_ACTORS_SHOWN = 10
MANUAL_HOME_MOVIES_SHOWN = MANUAL_HOME_ACTORS_SHOWN
DB_HOME_ACTORS_SHOWN = 5    # slower bc so many
DB_HOME_MOVIES_SHOWN = DB_HOME_ACTORS_SHOWN
DB_ACTORS_PG_SHOWN_PER_PAGE = 10
DB_MOVIES_PG_SHOWN_PER_PAGE = DB_ACTORS_PG_SHOWN_PER_PAGE